### ISSUE TITLE
In v10 Cannot read properties of undefined (reading 'getFlag')

### ISSUE THREAD

**Issue by Zamrod** [PepijnMC/ElevationDragRuler#24]
**Describe the bug**
With Drag Ruler (the temporary v10 patch), Enhanced Terrain Layer, and Terrain Ruler turned on there's a bunch of errors. If you disable just DnD5e Drag Ruler Integration then it works without errors but all of the extra features are misisng.

The errors are:
```
TypeError: Cannot read properties of undefined (reading 'getFlag')
    at TerrainConfig.getConfiguredEnvironments (hook.js:4:46)
    at DnD5eSpeedProvider.getCostForStep (hook.js:365:49)
    at getCostFromSpeedProvider (api.js:111:31)
    at opts.costFunction (compatibility.js:30:58)
    at measure.js:55:13
    at Array.map (<anonymous>)
    at measureDistancesSquare (measure.js:34:18)
    at Object.measureDistances (measure.js:20:10)
    at measureDistances (compatibility.js:33:40)
    at DragRulerRuler.measure (foundry_imports.js:265:20)
    at DragRulerRuler.measure (ruler.js:69:20)
    at DragRulerRuler.scheduleMeasurement (foundry_imports.js:151:8)
    at DragRulerRuler.onMouseMove (foundry_imports.js:143:22)
    at Token5e.onEntityLeftDragMove (main.js:141:15)
    at Token5e.onEntityLeftDragMoveSnap (main.js:134:23)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:26367:45)
    at MouseInteractionManager._handleDragMove (foundry.js:26724:17)
    at MouseInteractionManager._handleMouseMove (foundry.js:26696:22)
    at a.emit (index.js:202:33)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerMove (interaction.min.mjs:8:17255)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerMove (interaction.min.mjs:8:16687)
```

and 

```
TypeError: Cannot read properties of undefined (reading 'getFlag')
    at TerrainConfig.getConfiguredEnvironments (hook.js:4:46)
    at DnD5eSpeedProvider.getCostForStep (hook.js:365:49)
    at getCostFromSpeedProvider (api.js:111:31)
    at opts.costFunction (compatibility.js:30:58)
    at measure.js:55:13
    at Array.map (<anonymous>)
    at measureDistancesSquare (measure.js:34:18)
    at Object.measureDistances (measure.js:20:10)
    at measureDistances (compatibility.js:33:40)
    at DragRulerRuler.measure (foundry_imports.js:265:20)
    at DragRulerRuler.measure (ruler.js:69:20)
    at DragRulerRuler.scheduleMeasurement (foundry_imports.js:151:8)
    at foundry_imports.js:160:82
```

**To Reproduce**
1. Move a token within an area of difficult terrain
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/12570777/192516164-86a4e6f9-707a-4467-9d3f-d5a07d95d7e0.png)
![image](https://user-images.githubusercontent.com/12570777/192516195-b87c0718-ee8e-4e8e-a506-04b292412495.png)

**Comment by PepijnMC** [comment]
I wasn't planning on supporting this 'unofficial' temporary fork of drag ruler, I sadly don't have a ton of free time to spend on module development. I will see if I can at least get it somewhat working and provide an optional download, but it will be an unsupported release which may or may not be buggy.

**Comment by PepijnMC** [comment]
I have made a new [branch](https://github.com/PepijnMC/ElevationDragRuler/tree/v10-patch) for this temporary patch. Since it's not an 'official' v10 update I won't push a full release, but manual installation instructions can be found at the linked page.

Since you are also using Enhanced Terrain Layer, please be mindful of one of its current bugs: https://github.com/ironmonk88/enhanced-terrain-layer/issues/101
I would avoid using the rectangle and ellipse drawing tools provided by that module and use the polygon or free drawing tools instead.
