### ISSUE TITLE
The first time you move a creature it appears to have no movement

### ISSUE THREAD

**Issue by Zamrod** [PepijnMC/ElevationDragRuler#32]
**Describe the bug**
After putting a token on the canvas, the first time you move it shows red as if it had no movement. If you move it a second time, it works.

**Screenshots**
![image](https://user-images.githubusercontent.com/12570777/198848319-bc9bb259-52f5-4b8d-bc7f-c127dd2383de.png)

**Additional context**
This is with version 1.8.2

**Comment by PepijnMC** [comment]
I can't reproduce the issue by creating a new token, it shows the correct movement speeds immediately for me. Are you sure you didn't accidentally hold `Q` right before starting to drag, this is the default hotkey to force a token to use its teleport movement (which would be zero if not set up)? If that's not it could you try to replicate the issue again step by step?

**Comment by Zamrod** [comment]
It also gives the following error:
```
api.js:99 
        
       Error: This is not a registered game setting
    at ClientSettings.get (foundry.js:2758:42)
    at getRangesFromSpeedProvider (api.js:92:32)
    at DragRulerRuler.dragRulerGetColorForDistance (ruler.js:468:28)
    at DragRulerRuler.highlightMeasurementTerrainRuler (compatibility.js:12:22)
    at DragRulerRuler.performPostPathfindingActions (ruler.js:198:40)
    at DragRulerRuler.measure (ruler.js:133:16)
    at DragRulerRuler.scheduleMeasurement (foundry_imports.js:153:8)
    at DragRulerRuler.onMouseMove (foundry_imports.js:145:22)
    at Token5e.onEntityLeftDragMove (main.js:159:37)
    at Token5e.onEntityLeftDragMoveSnap (main.js:153:23)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:27702:45)
    at MouseInteractionManager._handleDragMove (foundry.js:28059:17)
    at MouseInteractionManager._handleMouseMove (foundry.js:28031:22)
    at a.emit (index.js:202:33)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerMove (interaction.min.mjs:8:17255)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerMove (interaction.min.mjs:8:16687)
```

**Comment by Ikabodo** [comment]
I'm having the same issue.

![image](https://user-images.githubusercontent.com/7766890/198850681-1947bdea-48c5-414c-a08e-766983066d88.png)

**Comment by Ikabodo** [comment]
I'm having the same issue.

**Comment by PepijnMC** [comment]
I unfortunately still can't reproduce the issue on my end even after importing your actor, but I'm starting to get the feeling it might be an annoying race condition between Drag Ruler and my module both wrapping the same function with libwrapper.

Could either of you go to Configure Settings and open the libWrapper Setting Menu:
![image](https://user-images.githubusercontent.com/13134303/198851204-b1cbfa08-a869-46eb-8508-1ce3584d90df.png)

From there could you prioritize DnD5e Drag Ruler Integration and save. Does the issue still persist?

**Comment by Ikabodo** [comment]
I tried this, it still happens unfortunately.

**Comment by PepijnMC** [comment]
Yeah I feared but it was worth a shot. If that had been the issue it should happen to all tokens, but it seems to only happen to a few judging from your video.

The error suggests the issue occurs when drag ruler tries to retrieve a color setting, I did notice I had a trailing comma in my color array and I believe some browsers still don't like it even though it's technically "allowed". I will remove the comma and put out a new release just in case that was truly it. If it still happens just let me know and I will do a deep dive tomorrow.

**Comment by Zamrod** [comment]
That seemed to fix it

**Comment by PepijnMC** [comment]
Looking at it again (I can't help myself) it might be a race condition within my own module, because setting flags can be a slow process and it might not be waiting for it before moving on, which could indeed cause issues with only specific tokens and users (tokens with a lot of data on them already and the processing power of the pc). I will keep the default movement mode regardless, it's not bad to have as a catch all but I will put out yet another release to await the setting of the flag to hopefully truly squash this mysterious bug once and for all.

I will keep this issue open for a while just in case too.
