### ISSUE TITLE
Massive bug with Enhanced Terrain Layer/Terrain Ruler

### ISSUE THREAD

**Issue by GambetTV** [PepijnMC/ElevationDragRuler#46]
With your module, Drag Ruler, Enhanced Terrain, Terrain Ruler, and libwrapper and socketlib on the most recent version of Foundry, if I drag a token into an area of difficult terrain, it's like they hit a wall, the game largely freezes, and I start getting serious errors. Disabling your module fixes the errors.

'libWrapper-wrapper.js:669 Uncaught TypeError: Cannot read properties of undefined (reading 'walk')
[Detected 5 packages: elevation-drag-ruler, enhanced-terrain-layer, terrain-ruler, drag-ruler, lib-wrapper]
    at rule_provider.js:44:114
    at Array.forEach (<anonymous>)
    at DnD5eRuleProvider.calculateCombinedCost (rule_provider.js:32:13)
    at calculateCombinedCost (api.js:121:38)
    at TerrainLayer.costWithTerrain (terrainlayer.js:287:26)
    at TerrainLayer.cost (terrainlayer.js:297:21)
    at getCostEnhancedTerrainlayer (measure.js:26:24)
    at measure.js:203:17
    at Array.reduce (<anonymous>)
    at measure.js:193:60
    at Array.map (<anonymous>)
    at measureDistancesGridless (measure.js:179:18)
    at Object.measureDistances (measure.js:18:10)
    at Token5e.applyGridlessSnapping (main.js:234:16)
    at Token5e.onEntityLeftDragMoveSnap (main.js:152:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:27813:45)
    at MouseInteractionManager._handleDragMove (foundry.js:28170:17)
    at MouseInteractionManager._handleMouseMove (foundry.js:28142:22)
    at a.emit (index.js:202:33)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerMove (interaction.min.mjs:8:17255)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerMove (interaction.min.mjs:8:16687)'

**Comment by PepijnMC** [comment]
Does the issue occur with all tokens and new tokens/actors? I can not reproduce the issue myself and there are no reproduction steps provided. 

If the issue is isolated to one or a few tokens it's most likely their terrain configuration got messed up somehow. Could you go into the token configuration menu of a token with the issue and look at the terrain tab to see if there's anything odd going on there?

**Comment by PepijnMC** [comment]
As a note, I have been noticing other odd issues with Foundry 10.291. If you can I would downgrade to 10.290.

**Comment by GambetTV** [comment]
It happens with brand new tokens and old tokens alike. However, I have noticed that it seems to be an issue with old pieces of terrain I laid down prior to these latest updates. Possibly even prior to my upgrade to v10 from about a month ago, but I can't say for sure about that. Going into each piece of terrain and opening up their settings and then clicking "Update Terrain" seems to fix this problem, though. So right now I think I'm just going to chalk it up to an update temporarily breaking something and move on. But if it starts happening again I'll let you know.

**Comment by PepijnMC** [comment]
Very odd and yes please let me know if it ever pops up again!
